<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Registration" duration-ms="27297" started-at="2019-03-18T13:12:12Z" finished-at="2019-03-18T13:12:40Z">
    <groups>
    </groups>
    <test name="Happy Registration Scenario" duration-ms="27297" started-at="2019-03-18T13:12:12Z" finished-at="2019-03-18T13:12:40Z">
      <class name="tests.RegisterTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:tests.RegisterTests@28f6a008]" name="setup" is-config="true" duration-ms="15560" started-at="2019-03-18T13:12:12Z" finished-at="2019-03-18T13:12:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="registerWithExistedEmail()[pri:1, instance:tests.RegisterTests@28f6a008]" name="registerWithExistedEmail" duration-ms="5883" started-at="2019-03-18T13:12:28Z" finished-at="2019-03-18T13:12:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Register]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Register]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at tests.RegisterTests.registerWithExistedEmail(RegisterTests.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerWithExistedEmail -->
        <test-method status="PASS" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:tests.RegisterTests@28f6a008]" name="screenshotOnFailure" is-config="true" duration-ms="99" started-at="2019-03-18T13:12:34Z" finished-at="2019-03-18T13:12:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=registerWithExistedEmail status=FAILURE method=RegisterTests.registerWithExistedEmail()[pri:1, instance:tests.RegisterTests@28f6a008] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="PASS" signature="registerWithValidData()[pri:2, instance:tests.RegisterTests@28f6a008]" name="registerWithValidData" duration-ms="5568" started-at="2019-03-18T13:12:34Z" finished-at="2019-03-18T13:12:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerWithValidData -->
        <test-method status="PASS" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:tests.RegisterTests@28f6a008]" name="screenshotOnFailure" is-config="true" duration-ms="1" started-at="2019-03-18T13:12:40Z" finished-at="2019-03-18T13:12:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=registerWithValidData status=SUCCESS method=RegisterTests.registerWithValidData()[pri:2, instance:tests.RegisterTests@28f6a008] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:tests.RegisterTests@28f6a008]" name="closeBrowser" is-config="true" duration-ms="153" started-at="2019-03-18T13:12:40Z" finished-at="2019-03-18T13:12:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.RegisterTests -->
    </test> <!-- Happy Registration Scenario -->
  </suite> <!-- Registration -->
</testng-results>
